---
title: "Relatório Gerencial 2"
author: "Vinicius Deolindo de Sousa - Cientista de dados"
date: "Maio/2019"
output:
  MyTemplates::my_html_format:
    toc: true
---

# Sobre o relatório

O relatório contém analise de dados, estatísticas e uma simulação de forecast com algoritmo Xgboost:

- Analise de dados: O comportamento da serie histórica e analise de gráficos.
- Estatísticas: Verificação de padrões ao longo do tempo.
- Forecast: Modelagem de dados com Xgboost o modelo mais utilizado por cientista de dados no mundo.

# Informações sobre os dados

Os dados foram extraídos da API de dados financeiros do site yahoo!:

- A custom HTML footer, which is stored in `inst/rmarkdown/resources/footer.html`.
- A custom HTML header, which is stored in `inst/rmarkdown/resources/header.html`. This adds a logo to the header of the document.
- A custom styles file `inst/rmarkdown/resources/styles.css`, which alters the appearance of tables.

# Analises

The custom CSS file has been used to change the style of the document. Here is an example table:

```{r table}
knitr::kable(mtcars[1:5, 1:5], caption = "An example table")
```

# Resumo

As some ideas for using this template, you may wish to customise your own document:

- Change the default options used in the `my_html_format` function. For example, it will use the theme "lumen", but this could be changed to "yeti", "sandstone" etc.
- Update the footer file to include your own name and email address, and edit the urls for the social media icons so that they they link to your account.
- Add your own logo by altering the `header.html` file. You will notice that the URL is referenced as a URL: this is recommended as it makes your package more portable.




